// -------------------------------------------------------------
// 
// File Name: hdlsrc\adder\adder.v
// Created: 2026-04-13 14:33:47
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0
// Target subsystem base rate: 0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: adder
// Source Path: adder
// Hierarchy Level: 0
// Model version: 1.2
// 
// -------------------------------------------------------------

module adder(
    input [7:0] a,
    input [7:0] b,
    input c_in,
    output [7:0] sum,
    output c_out
);

wire [8:0] carry;

assign carry[0] = c_in;

genvar i;
generate
    for(i=0; i<8; i=i+1) begin
        assign sum[i] = a[i] ^ b[i] ^ carry[i];
        assign carry[i+1] = (a[i] & b[i]) | (b[i] & carry[i]) | (a[i] & carry[i]);
    end
endgenerate

assign c_out = carry[8];

endmodule

